node_modules/oae-core/notifications/css/notifications.css
node_modules/oae-core/notifications/js/notifications.js
node_modules/oae-core/topnavigation/topnavigation.html

The "Notifications" icon (), when selected, opens a drop down of recent notifications. While the drop down is accessible by keyboard, users can only access it after they have navigated through the entire page. Keyboard focus should be set to the dropdown content upon selecting the icon or, optimally, the underlying code should be rearranged to ensure the dropdown content comes immediately after the icon instead of at the end of the page.

(A11y severity 2) Associate notifications dropdown content more closely with icon

---

shared/oae/api/oae.api.util.js

Some URLs are not being recognised correctly in the Markdown comments:

Markdown parsing link issue

---

shared/vendor/js/bootstrap-plugins/bootstrap.notify.oae-edited.js

Whenever an action is completed (e.g., uploading a file, deleting a file, invoking an error, etc.) a banner briefly appears.
This information is not presented to screen reader users. This can be accomplished setting `role="alert"` on the element. This will cause it to be read immediately when the element appears and the alert role is set.
* Ensure that the alert role is reset (i.e., set to a new element, or the role changed or removed if using one element with differing content) after the information has been presented to the user. Not resetting the alert can lead to subsequent alerts not being read by screen readers.
* Alternatively, focus can be set directly to the notification area. In this case, the element must not automatically disappear after a period of time. Instead, the user …

(A11y severity 2) Make push notifications accessible 

---

node_modules/oae-core/documentpreview/bundles/default.properties
node_modules/oae-core/documentpreview/documentpreview.html

The page number text box does not have an associated label. Because there is no text next to this field that informs the user to the purpose of the textbox (e.g., "Enter page number "), the label will need to be hidden off-screen using CSS (see webaim.org/techniques/css/invisiblecontent/) or the field given a descriptive `title` or `aria-label` attribute.

(A11y severity 2) Label page number input in document preview

---

node_modules/oae-core/createlink/js/createlink.js
node_modules/oae-core/upload/js/upload.js

When a user navigates to the file name after selecting it, a tooltip appears visually (Click to rename), but this information is not presented to screen reader users. This field may be associated to the element via `aria-describedby`.

(A11y severity 2) Tooltip accessibility

---

shared/oae/js/jquery-plugins/jquery.clip.js
shared/oae/js/jquery-plugins/jquery.list.js
shared/oae/macros/list.html
ui/content.html
ui/discussion.html
ui/folder.html
ui/group.html
ui/me.html

Several of the expandable buttons on the site (e.g. clips) do not inform screen reader users that the button expands a menu. Additionally, the state of the expansion (e.g., expanded, not expanded) is not conveyed. Providing this information aids users who are unable to see how the controls are meant to function. Add `aria-expanded` with the appropriate true or false values to all buttons that control expansion.

(A11y severity 2) Add ARIA markup to expandable content

---

node_modules/oae-core/upload/js/upload.js

When a user selects a file to upload in the "Upload file(s)" modal, the modal changes causing keyboard focus to be lost. Once keyboard focus is lost, the user essentially becomes trapped and cannot navigate at all. Ensure that keyboard focus is set to a logical place within the modal once a file has been selected.

(A11y severity 1) Preserve keyboard focus on file uploads

---

node_modules/oae-core/comments/comments.html

While nested comments are apparent visually, there is no indication of these relationships available to screen readers.
 A nested relationship could be conveyed through the use of either unordered lists or by heading structure. Unordered lists may be the most appropriate in this situation since the first comment begins with a fourth-level heading which doesn’t leave much room for sub-headings. Using unordered lists would provide the nesting concept by ensuring that each sub-comment is a list item for each parent comment. No changes to the visual presentation would be necessary (styles can be used to suppress the list bullets, etc.). Present the nested relationship information to users in a way that conveys the same information available visually.

(A11y severity 3) Add markup hierarchy to comment threads

---

node_modules/oae-core/topnavigation/topnavigation.html
shared/oae/macros/list.html
ui/index.html
ui/search.html

When using iOS, the label on the submit button in the iOS keyboard reads "return". Is it possible to modify this to make it say "Search" instead?

Adjust 'return' label on iOS

---

shared/oae/css/oae.components.css

I have 1 folder shared with me.
I went into a collaborative document and selected to "Add to Folder". When I select the folder to which I want to add it, it gets a weird asymmetric blue border. Notice that I have switched focus to the "My Library" tab, which indicates that the blue border is *not* the browser's focus border.
Chrome 40.0.2214.111 Mac OSX

Weird blue border around folder selection

---

shared/oae/api/oae.api.js
shared/oae/css/oae.base.css
shared/oae/js/jquery-plugins/jquery.infinitescroll.js

There was a race condition where the $.dotdotdot plugin gets invoked while the body is not made visible yet. This change re-uses another area of `search.js` that seems to be listening for the same quirk.
Since `$('body').show()` seems to be in nature asynchronous, so it would be good to take some kind of event-driven approach to better trigger when the widgets have loaded.

Wait for body to be visible before applying $.dotdotdot

---

node_modules/oae-core/upload/js/upload.js

`replaceFileInput` was still necessary. Verified file upload still works on Firefox, as removing it had something to do w/ Firefox.

(Issue #3986) Don't disable the file upload input when the form is submit

---

node_modules/oae-core/aboutcontent/tests/aboutcontent.js
node_modules/oae-core/createcollabdoc/js/createcollabdoc.js
node_modules/oae-core/deleteresource/tests/deleteresource.js
node_modules/oae-core/etherpad/js/etherpad.js
node_modules/oae-core/filepreview/tests/filepreview.js
node_modules/oae-core/manageaccess/js/manageaccess.js
node_modules/oae-core/manageaccess/manageaccess.html
node_modules/oae-core/revisions/tests/revisions.js
shared/oae/api/oae.api.content.js
shared/oae/bundles/ui/default.properties
shared/oae/macros/tests/metadata.js
tests/casperjs/util/include/content.js
ui/js/content.js
ui/tests/content.js

- When managing the members of a collaborative document, the "Can edit" role should be available as one of the roles
- When sharing a collaborative document as a manager, the editor role should be available as one of the roles in the dropdown
- When sharing a collaborative document as an editor, the editor role should be available as one of the roles in the dropdown
- When creating a new collaborative document, all groups and users the item is shared with should become editors

Add editor role to the UI

---

node_modules/oae-core/groupprofile/css/groupprofile.css

Given the text `ThisIsSomeReallyLongTextWithoutASpaceOrLinebreakToSeeHowItRespondsWithWrapping` I get the following in Chrome (OS X):
Some word wrapping should be applied

Group descriptions should wrap on their profile page

---

node_modules/oae-core/manageaccess/js/manageaccess.js
shared/oae/api/oae.api.util.js

1. Create a group
2. Click manage access
3. Add several users, including the group itself
* Note that another issue we should resolve is that the group itself doesn't show up in auto-suggest
* This serves as a way to trigger a 400 error when you save the membership changes
4. Save the membership changes, there is an error because the group was being added to itself
5. Remove the group from the list
6. Click save. Still an error because it's still trying to add the group
7. Remove all the other users you tried to add and click save, all the members you removed are still part of the POST request

When an error occurs during manageacces, removed members still stay cached for adding users

---

node_modules/oae-core/userdetails/bundles/default.properties
node_modules/oae-core/userdetails/js/userdetails.js
node_modules/oae-core/userdetails/userdetails.html
shared/oae/api/oae.api.util.js
shared/oae/bundles/ui/default.properties

The userdetails widget should be extended to also consider display names with an `@` to be invalid. When going through the Shibboleth responses that we've received so far, I noticed quite a few that only release a targeted-id in the form of `...=@surrey.ac.uk`.

Extend userdetails to catch display names with @

---

shared/oae/api/oae.api.util.js

When using Internet Explorer 11, the "Add" button is disabled on the *popup* when trying to share a document with other users/groups.
The issue may be related to the use of the remove() method which is apparently not supported in IE:

["Manage access" popup] "Add" button is not clickable on Internet Explorer 11

---

node_modules/oae-admin/createuser/js/createuser.js
node_modules/oae-core/register/js/register.js

The Sign Up modal doesn't allow an email address as the username because the `@` is considered to be an invalid character. However, we want to allow email addresses as usernames and the REST API already supports this.

Sign Up modal doesn't allow email address as username

---

node_modules/oae-core/activity/activity.html
node_modules/oae-core/activity/css/activity.css
node_modules/oae-core/lhnavigation/js/lhnavigation.js
shared/oae/css/oae.components.css
shared/oae/css/oae.skin.less
shared/oae/js/jquery-plugins/jquery.infinitescroll.js
shared/oae/macros/list.html

The content within the "Recent Activity" section could benefit from a better heading structure. For example, the first line at the start of each activity should be marked up as a second-level heading (it is currently not a heading). This will allow users to more effectively navigate this page.

(A11y severity 3) Improve structure of activity stream content

---

node_modules/oae-admin/manageuser/js/manageuser.js
node_modules/oae-admin/manageuser/manageuser.html
node_modules/oae-core/preferences/js/preferences.js
node_modules/oae-core/preferences/preferences.html
shared/oae/bundles/ui/default.properties
shared/oae/css/oae.skin.less

The OAE back-end has an option to turn off email notifications for a user, but it’s currently not exposed in the UI to discourage users from turning them off. You can currently turn off email notifications through the REST API and the Swagger documentation page, but we should also expose this as a fourth email notification option in the manageuser widget.
The fa-ban icon can be used for the new option.

Allow email notifications for user to be turned off in admin UI

---

node_modules/oae-core/editprofile/js/editprofile.js
node_modules/oae-core/termsandconditions/js/termsandconditions.js
shared/oae/api/oae.api.js
shared/oae/api/oae.api.user.js

I think the POST to accept invitations triggers a T&C modal while the email modal is showing.
Additionally, I'm not sure if the accept invitation request is going to work anyway with external login when T&C is needed as T&C needs to be accepted before the invitation.

Two modals display if accepting invitation, don't have email (signin with twitter) and need to accept T&C

---

shared/oae/api/oae.api.js

When the user is not already signed in to the OAE and they click on the "Verify my email" button in the email verification email, they are not presented the signin option when they arrive at the OAE, and there is no longer any redirect url to accept the verification.
Previously, redirecting to `/me` would cause a redirect to `/` with a `?url=` parameter for redirect. We should try and do something similar on the `/` page, however it will be a bit trickier because we need to reliably determine when to redirect. If we just send directly to `/?url=...`, then that might not have the desired effect when the user is already signed in.

Cannot confirm email unless you are already signed in

---

shared/oae/api/oae.api.util.js
ui/js/signup.js
ui/signup.html

Now that WAYF is merged, it is possible to transfer your invitation from the network tenant to another, and accept it there.
This also means that a user may want to accept an invitation from the gmail account, which takes them to the network tenant, then head over to their unadopted umichigan tenant to create an account with email address umich.edu. However since the invitation has a gmail.com email address, the email address field on the signup form is not present.

Show email address field if invitation email domain is not valid for the current tenant

---

node_modules/oae-core/deletefolder/js/deletefolder.js
node_modules/oae-core/deleteresource/js/deleteresource.js

Report:
> Today I created a document, pasted in some text, disliked the formatting and so clicked the Delete button. I got the message saying the document had been deleted, but it remained on screen and I could continue to work with the text; I got error messages if I tried to share or delete it (again). When I clicked away and tried to come back it had gone.
I can't remember if we ever did redirect them away. Where would we send them? Should the back-end provide some feedback to determine which group (if any) to redirect the user to? Should we always redirect them to their activity page?

Deleted resource not redirecting user away

---

node_modules/oae-core/topnavigation/js/topnavigation.js
node_modules/oae-core/topnavigation/topnavigation.html

See video for specifics: https://youtu.be/ePAc6WiazfA
When our students navigate to OAE by a link and are not signed in, they cannot post.  When they click sign in, instead of it keeping them where they wanted to post/contribute, they are redirected back to their recent activity.  In many cases, they have to retrace their steps to click the link again to get to where they needed to be.

OAE redirects to activity page when not signed in (instead of staying on the page you needed)

---

node_modules/oae-core/activity/css/activity.css
shared/oae/css/oae.components.css

Reported by @D7Torres:
As you can see, the padding of the icon of the tile is overflowing the tile, because the margin is negative. My problem was, if you try to click in the button you could click the tile instead. You could even click a tile of the first road and actually being clicking the tile below, in the second row.
They only thing I had to do to solve it was changing this styles in `oae.components.css`
```
.oae-tile .oae-thumbnail.oae-thumbnail-large:before {
margin-top: -48px;
padding-top: 80px;
}
```
to 
```
.oae-tile .oae-thumbnail.oae-thumbnail-large:before {
margin-top: -0px;
padding-top: 32px;
}
```

Tile margin issue

---

shared/oae/js/jquery-plugins/jquery.infinitescroll.js

When the UI requests a folder library, if the results array is empty, it will stop requesting regardless if there is a `nextToken` defined by the back-end.
It should continue requesting items until the `nextToken` is falsey.

Folder library not requesting more items when `nextToken` is specified

---

shared/oae/api/oae.api.authentication.js

Fixes issue #4092. As a sidenote, I tried to open this using  `git pull-request -i 4092 -b oaeproject/3akai-ux:master -h sallakarppinen/3akai-ux:issue-4092 -m 'Hides the Sign in-button on 401 page'` but it failed to link to the issue automatically (I've aliased hub as git).

Hides the Sign in-button on 401 page

---

node_modules/oae-core/discussion/js/discussion.js
node_modules/oae-core/groupprofile/groupprofile.html
shared/oae/api/oae.api.util.js
shared/oae/css/oae.base.css

We currently render markdown in comments (I think it's client-side), we should add that handling in these areas as well to make it more consistent.

Group description (About) and discussion description should both support markdown

---

node_modules/oae-core/discussion/css/discussion.css
node_modules/oae-core/groupprofile/css/groupprofile.css

From bugbash: tables in comments display very different than in description. @SamPeck supplied alternative values for the main container (see below).

Markdown tables should use alternative CSS in description

---

shared/oae/api/oae.api.util.js
shared/oae/errors/js/accessdenied.js
shared/oae/errors/js/notfound.js

This fixes #4142.
EDIT: To clarify, it stops the browser back button from taking you to etherpad. The back button on the page itself will still do nothing (although I'm not sure if that's a problem - it's a new tab so there's no history for it to take you to).

Use `window.location.replace` to eliminate need to manipulate history

---

Gruntfile.js
package.json

Requirejs optimize no longer uglifies
Now using uglify-es and grunt-contrib-uglify-es instead of requirejs

Fixes #4199
