ui/js/index.js
Skinning isn't being applied correctly to the lower left block.
=> Skinning error in configurable landing pages

node_modules/oae-core/topnavigation/js/topnavigation.js, node_modules/oae-core/topnavigation/topnavigation.html
All top navigation buttons should have a standard tooltip (e.g. Notifications, Sign out, etc.)
=> Top navigation buttons should have tooltip

node_modules/oae-core/lhnavigation/js/lhnavigation.js, shared/oae/api/oae.bootstrap.js, shared/oae/api/oae.core.js, shared/oae/css/oae.components.css, shared/oae/js/jquery-plugins/jquery.infinitescroll.js, shared/oae/macros/list.html, shared/vendor/js/jquery-plugins/jquery.dotdotdot.js
Improved item name readability: allow tiles to show multiple lines of the item name
=> Allow tiles to show multiple lines of the item name

shared/oae/macros/list.html
The threedotting is not applied correctly in the upload widget:
=> Threedotting problem in upload widget

shared/oae/api/oae.api.authentication.js
UI counter-part of https://github.com/oaeproject/Hilary/pull/1140
=> Renamed Google auth’s `hostedDomain` to `domains`

ui/css/oae.index.css, ui/index.html
Add configuration options for horizontal and vertical alignment in landing page blocks
=> Add configuration options for horizontal and vertical alignment in landing page blocks

node_modules/oae-core/footer/footer.html
Fix for https://github.com/oaeproject/3akai-ux/issues/4011
=> Html encode footer instance info

node_modules/oae-core/deletecomment/deletecomment.html, node_modules/oae-core/deletefolder/deletefolder.html, node_modules/oae-core/deleteresource/deleteresource.html, shared/oae/api/oae.api.widget.js
The following error shows up in the console:
```
Uncaught Error: Syntax error, unrecognized expression: 
<div id="deleteresource-modal" class="modal fade" tabindex="-1" aria-labelledby="deleteresource-modal-title" aria-hidden="true"></div>
<div id="deleteresource-template"></div>
<div id="deleteresource-notification-title-template"></div>
<div id="deleteresource-notification-body-template"></div>
<script type="text/javascript" src="https://qa0-researchresearch-researchresearch.netdna-ssl.com/node_modules/oae-core/deleteresource/js/deleteresource.1398ef31.js"></script>
```
=> Error deleting a group

node_modules/oae-core/linkpreview/js/linkpreview.js, shared/vendor/js/jquery-plugins/jquery.oembed.js
UI counter part of https://github.com/oaeproject/Hilary/pull/1139
=> Use our own URL expander and update the jQuery oembed plugin

shared/oae/errors/noscript.html, shared/oae/errors/servermaintenance.html, shared/oae/errors/unavailable.html
Transferred from https://github.com/oaeproject/puppet-hilary/issues/163#event-360029992
=> Server maintenance page is blank

node_modules/oae-core/sharedwith/js/sharedwith.js
- There should be some space between the footer and the activity item above it
- Uploading a profile picture does not appear to be working. In fact, it doesn't look like any uploads work.
- There's no spacing between individual items in the invitation email
- The Share With modal doesn't render for a discussion
=> (InvitingGuests) IE9 issues

ui/js/signup.js
I really have no idea how this got through my dev testing. I suspect I made some late changes and didn't test the case where there was no email domain for the tenant :(
=> Fix issue with no tenant email domain and no invitation email

shared/oae/errors/accessdenied.html, shared/oae/errors/js/accessdenied.js
=> `Sign in` button should not be visible for logged in users

node_modules/oae-admin/manageuser/bundles/default.properties, node_modules/oae-admin/manageuser/css/manageuser.css, node_modules/oae-admin/manageuser/js/manageuser.js, node_modules/oae-admin/manageuser/manageuser.html, shared/oae/api/oae.api.authentication.js
=> Manageuser widget should provide list of all associated LoginIds for a user

node_modules/oae-admin/skinning/bundles/default.properties, node_modules/oae-admin/skinning/css/skinning.css, node_modules/oae-admin/skinning/js/skinning.js, node_modules/oae-admin/skinning/skinning.html
UI changes related to the Hilary issue #1296.
=> UI for adding a tenant logo via the admin site

ui/css/oae.search.css, ui/js/search.js
Related to [Hilary issue 1295](https://github.com/oaeproject/Hilary/issues/1295).
=> The "this tenant only" checkbox in the UI should be hidden for private tenants

node_modules/oae-core/linkpreview/js/linkpreview.js
needs https://github.com/oaeproject/Hilary/pull/1107
=> check that the browser supports a link content-type before embedding

shared/oae/bundles/ui/default.properties, shared/oae/errors/accessdenied.html, shared/oae/errors/css/oae.error.css, shared/oae/errors/js/accessdenied.js, shared/oae/errors/js/notfound.js, shared/oae/errors/notfound.html
=> Added back button to 404 and 401 pages

ui/js/resetpassword.js
=> Refactoring of the resetpassword feature

nginx/nginx.conf, nginx/nginx.conf.docker, nginx/self-signed.conf, nginx/ssl-params.conf, package.json
Frontend follow-up for PR [#1349](https://github.com/oaeproject/Hilary/pull/1349)
=> Docker-based development environment

node_modules/oae-core/resetpassword/js/resetpassword.js, node_modules/oae-core/signin/signin.html
=> Fixed issue where @ not accepted in usernames

node_modules/oae-core/aboutgroup/aboutgroup.html
=> Fixed group about modal

node_modules/oae-core/preferences/bundles/default.properties, node_modules/oae-core/preferences/css/preferences.css, node_modules/oae-core/preferences/preferences.html
=> Added option for users to never receive emails

.travis.yml, package.json
=> fixes #4170

.circleci/config.yml, node_modules/oae-core/listlti/js/listlti.js, node_modules/oae-jitsi-widgets/meeting-jitsi/js/meeting-jitsi.js, shared/oae/api/oae.api.authentication.js, ui/js/resetpassword.js
Currently just does `grunt` and `grunt jshint`, but should already be of some benefit (particularly the linting part).
=> Add CircleCI config

.circleci/config.yml
=> fixed circleci script, hopefully

node_modules/oae-core/signin/js/signin.js, shared/oae/api/oae.api.tenancysearch.js
=> Fixes #4196

Gruntfile.js
=> Fixes #4199 for good

node_modules/oae-core/signin/js/signin.js
=> Fixes #4196 for good

Gruntfile.js
Words fail me 🤦‍♂️
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oaeproject/3akai-ux/4202)
=> Fixes issue #4199 for good for the second time

packages/oae-core/manageaccess/bundles/default.properties, shared/oae/js/activityadapter.js
Post-merge fixes to issue #1402
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oaeproject/3akai-ux/4215)
=> fix: a couple of fixes to previous merge

nginx/nginx.conf.docker
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oaeproject/3akai-ux/4217)
=> fix(ethercalc): support for multi-server ethercalc

nginx/nginx.conf.docker
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oaeproject/3akai-ux/4218)
=> fix(ethercalc): add a missing nginx location directive

shared/oae/js/activityadapter.js
Fixes #4225
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oaeproject/3akai-ux/4226)
=> fix: activity summary is now returned

packages/oae-core/editprofile/bundles/fr_FR.properties
Fixes #4228
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oaeproject/3akai-ux/4229)
=> chore: fixed translation issue

crowdin.yml, packages/oae-admin/adminheader/bundles/fr_FR.properties, packages/oae-admin/configuration/bundles/fr_FR.properties, packages/oae-admin/createtenant/bundles/fr_FR.properties, packages/oae-admin/createuser/bundles/fr_FR.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oaeproject/3akai-ux/4233)
=> L10n master5

packages/oae-core/revisions/js/revisions.js, packages/oae-core/revisions/revisions.html
Fixes https://github.com/oaeproject/Hilary/issues/1966
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oaeproject/3akai-ux/4238)
=> fix: revision modal now displays previews for ethercalc docs

packages/oae-admin/maintenance/bundles/default.properties, packages/oae-admin/maintenance/bundles/fr_FR.properties, packages/oae-admin/maintenance/js/maintenance.js, packages/oae-admin/maintenance/maintenance.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oaeproject/3akai-ux/4239)
=> feat: new ability to reprocess a specific contentId

nginx/nginx.conf, nginx/nginx.docker.conf
Fixes #4262
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oaeproject/3akai-ux/4263)
=> chore: changed default port to match Hilary's
